const newDiv=document.createElement('Div');
newDiv.setAttribute('title','helloDiv');
const newTextNode=document.createTextNode('Hello');
newDiv.appendChild(newTextNode);
const container=document.querySelector('header .container');
const h1=document.querySelector('h1');
container.insertBefore(newDiv,h1);
const newDiv1=document.createElement('Div');
newDiv1.setAttribute('title','helloDiv');
const newTextNode1=document.createTextNode('Hello');
newDiv1.appendChild(newTextNode1);
const ul=document.querySelector('ul');
const li=document.querySelector('li:first-child');
ul.insertBefore(newDiv1,li);